name: Swift

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Test THEPageControl
              run: ./scripts/test.sh
            - name: Build THEPageControlApp
              run: ./scripts/build_app.sh
