name: Swift

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build THEPageControl
              run: ./scripts/build.sh
            - name: Build THEPageControlApp
              run: ./scripts/build_app.sh
